//
// Generated file, do not edit! Created by nedtool 4.6 from src/Base/Messages/icancloud_Message.msg.
//

#ifndef _ICANCLOUD_MESSAGE_M_H_
#define _ICANCLOUD_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <list>
#include <string>
#include "icancloud_types.h"
	
	
   /**
	* Structure that represents a trace piece.
	*/
	struct TraceComponent{
		int moduleID;						/**< Module ID */
		int gateID;							/**< Gate ID to moduleID */
		std::list <reqNum_t> reqSequence;	/**< Requests sequence */
		
		
	   /**
		* Assignment operator
		* @param other Trace component
		*/
		TraceComponent& operator=(const TraceComponent& other);	
		
	   /**
		* Constructor
		* @param newModule Module ID
		* @param newGate Gate ID		
		*/
		TraceComponent (int newModule, int newGate); 
		
	   /**
		* Constructor
		* @param newModule Module ID
		* @param newGate Gate ID
		* @param newReq Request number		
		*/
		TraceComponent (int newModule, int newGate, reqNum_t newReq);		
	};
// }}

/**
 * Class generated from <tt>src/Base/Messages/icancloud_Message.msg:50</tt> by nedtool.
 * <pre>
 * ///
 * /// icancloud Message Base definition
 * ///
 * message icancloud_Message extends cPacket
 * {
 *     @customize(true);
 * 
 *     unsigned int operation = -1;						// Operation type
 *     bool isResponse = false;							// Is a response message?
 *     bool remoteOperation = false;						// Is a remote operation?		
 * 
 *     int connectionId = -1;								// Connection ID (Used in remote operation between nodes)
 *     int commId = -1;									// Communication ID (Used to locate a communication with server)
 *     unsigned int sourceId = NULL_PROCESS_ID;			// ID from the source process
 * 
 *     unsigned int nextModuleIndex = -1;					// Array index destination module.				
 *     int result = 0;										// Operation result.
 * 
 *     abstract TraceComponent trace[];					// Message trace		
 * 
 *     int uid = -1;										// user id
 *     int pid = -1;										// processId id	
 * }
 * </pre>
 *
 * icancloud_Message_Base is only useful if it gets subclassed, and icancloud_Message is derived from it.
 * The minimum code to be written for icancloud_Message is the following:
 *
 * <pre>
 * class icancloud_Message : public icancloud_Message_Base
 * {
 *   private:
 *     void copy(const icancloud_Message& other) { ... }

 *   public:
 *     icancloud_Message(const char *name=NULL, int kind=0) : icancloud_Message_Base(name,kind) {}
 *     icancloud_Message(const icancloud_Message& other) : icancloud_Message_Base(other) {copy(other);}
 *     icancloud_Message& operator=(const icancloud_Message& other) {if (this==&other) return *this; icancloud_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual icancloud_Message *dup() const {return new icancloud_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from icancloud_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(icancloud_Message);
 * </pre>
 */
class icancloud_Message_Base : public ::cPacket
{
  protected:
    unsigned int operation_var;
    bool isResponse_var;
    bool remoteOperation_var;
    int connectionId_var;
    int commId_var;
    unsigned int sourceId_var;
    unsigned int nextModuleIndex_var;
    int result_var;
    int uid_var;
    int pid_var;

  private:
    void copy(const icancloud_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const icancloud_Message_Base&);
    // make constructors protected to avoid instantiation
    icancloud_Message_Base(const char *name=NULL, int kind=0);
    icancloud_Message_Base(const icancloud_Message_Base& other);
    // make assignment operator protected to force the user override it
    icancloud_Message_Base& operator=(const icancloud_Message_Base& other);

  public:
    virtual ~icancloud_Message_Base();
    virtual icancloud_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class icancloud_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getOperation() const;
    virtual void setOperation(unsigned int operation);
    virtual bool getIsResponse() const;
    virtual void setIsResponse(bool isResponse);
    virtual bool getRemoteOperation() const;
    virtual void setRemoteOperation(bool remoteOperation);
    virtual int getConnectionId() const;
    virtual void setConnectionId(int connectionId);
    virtual int getCommId() const;
    virtual void setCommId(int commId);
    virtual unsigned int getSourceId() const;
    virtual void setSourceId(unsigned int sourceId);
    virtual unsigned int getNextModuleIndex() const;
    virtual void setNextModuleIndex(unsigned int nextModuleIndex);
    virtual int getResult() const;
    virtual void setResult(int result);
    virtual void setTraceArraySize(unsigned int size) = 0;
    virtual unsigned int getTraceArraySize() const = 0;
    virtual TraceComponent& getTrace(unsigned int k) = 0;
    virtual const TraceComponent& getTrace(unsigned int k) const {return const_cast<icancloud_Message_Base*>(this)->getTrace(k);}
    virtual void setTrace(unsigned int k, const TraceComponent& trace) = 0;
    virtual int getUid() const;
    virtual void setUid(int uid);
    virtual int getPid() const;
    virtual void setPid(int pid);
};


#endif // ifndef _ICANCLOUD_MESSAGE_M_H_

