//
// Generated file, do not edit! Created by nedtool 4.6 from src/Base/Messages/icancloud_Migration_Message.msg.
//

#ifndef _ICANCLOUD_MIGRATION_MESSAGE_M_H_
#define _ICANCLOUD_MIGRATION_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "icancloud_App_NET_Message.h"
	#include <vector>
	
// }}

/**
 * Class generated from <tt>src/Base/Messages/icancloud_Migration_Message.msg:18</tt> by nedtool.
 * <pre>
 * //
 * // icancloud Message for migration requests
 * //
 * message icancloud_Migration_Message extends icancloud_App_NET_Message
 * {
 *     @customize(true);
 * 
 *     int memorySizeKB = 0;
 *     int diskSizeKB = 0;
 *     string virtualIP = "";
 * 
 *     bool remoteStorage = false;
 *     int standardRequests = 0;
 *     int deleteRequests = 0;
 *     int remoteStorageUsedKB = 0;
 * 
 * }
 * </pre>
 *
 * icancloud_Migration_Message_Base is only useful if it gets subclassed, and icancloud_Migration_Message is derived from it.
 * The minimum code to be written for icancloud_Migration_Message is the following:
 *
 * <pre>
 * class icancloud_Migration_Message : public icancloud_Migration_Message_Base
 * {
 *   private:
 *     void copy(const icancloud_Migration_Message& other) { ... }

 *   public:
 *     icancloud_Migration_Message(const char *name=NULL, int kind=0) : icancloud_Migration_Message_Base(name,kind) {}
 *     icancloud_Migration_Message(const icancloud_Migration_Message& other) : icancloud_Migration_Message_Base(other) {copy(other);}
 *     icancloud_Migration_Message& operator=(const icancloud_Migration_Message& other) {if (this==&other) return *this; icancloud_Migration_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual icancloud_Migration_Message *dup() const {return new icancloud_Migration_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from icancloud_Migration_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(icancloud_Migration_Message);
 * </pre>
 */
class icancloud_Migration_Message_Base : public ::icancloud_App_NET_Message
{
  protected:
    int memorySizeKB_var;
    int diskSizeKB_var;
    opp_string virtualIP_var;
    bool remoteStorage_var;
    int standardRequests_var;
    int deleteRequests_var;
    int remoteStorageUsedKB_var;

  private:
    void copy(const icancloud_Migration_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const icancloud_Migration_Message_Base&);
    // make constructors protected to avoid instantiation
    icancloud_Migration_Message_Base(const char *name=NULL, int kind=0);
    icancloud_Migration_Message_Base(const icancloud_Migration_Message_Base& other);
    // make assignment operator protected to force the user override it
    icancloud_Migration_Message_Base& operator=(const icancloud_Migration_Message_Base& other);

  public:
    virtual ~icancloud_Migration_Message_Base();
    virtual icancloud_Migration_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class icancloud_Migration_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMemorySizeKB() const;
    virtual void setMemorySizeKB(int memorySizeKB);
    virtual int getDiskSizeKB() const;
    virtual void setDiskSizeKB(int diskSizeKB);
    virtual const char * getVirtualIP() const;
    virtual void setVirtualIP(const char * virtualIP);
    virtual bool getRemoteStorage() const;
    virtual void setRemoteStorage(bool remoteStorage);
    virtual int getStandardRequests() const;
    virtual void setStandardRequests(int standardRequests);
    virtual int getDeleteRequests() const;
    virtual void setDeleteRequests(int deleteRequests);
    virtual int getRemoteStorageUsedKB() const;
    virtual void setRemoteStorageUsedKB(int remoteStorageUsedKB);
};


#endif // ifndef _ICANCLOUD_MIGRATION_MESSAGE_M_H_

