//
// Generated file, do not edit! Created by nedtool 4.6 from src/Base/Messages/icancloud_App_MEM_Message.msg.
//

#ifndef _ICANCLOUD_APP_MEM_MESSAGE_M_H_
#define _ICANCLOUD_APP_MEM_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "icancloud_Message.h"
			
// }}

/**
 * Class generated from <tt>src/Base/Messages/icancloud_App_MEM_Message.msg:15</tt> by nedtool.
 * <pre>
 * ///
 * /// icancloud Message for MEM requests
 * ///
 * message icancloud_App_MEM_Message extends icancloud_Message
 * {
 *     @customize(true);
 * 
 *     unsigned int memSize = 0;		// Amount of memory
 *     unsigned int region = 0;		// Region of memory
 * }
 * </pre>
 *
 * icancloud_App_MEM_Message_Base is only useful if it gets subclassed, and icancloud_App_MEM_Message is derived from it.
 * The minimum code to be written for icancloud_App_MEM_Message is the following:
 *
 * <pre>
 * class icancloud_App_MEM_Message : public icancloud_App_MEM_Message_Base
 * {
 *   private:
 *     void copy(const icancloud_App_MEM_Message& other) { ... }

 *   public:
 *     icancloud_App_MEM_Message(const char *name=NULL, int kind=0) : icancloud_App_MEM_Message_Base(name,kind) {}
 *     icancloud_App_MEM_Message(const icancloud_App_MEM_Message& other) : icancloud_App_MEM_Message_Base(other) {copy(other);}
 *     icancloud_App_MEM_Message& operator=(const icancloud_App_MEM_Message& other) {if (this==&other) return *this; icancloud_App_MEM_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual icancloud_App_MEM_Message *dup() const {return new icancloud_App_MEM_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from icancloud_App_MEM_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(icancloud_App_MEM_Message);
 * </pre>
 */
class icancloud_App_MEM_Message_Base : public ::icancloud_Message
{
  protected:
    unsigned int memSize_var;
    unsigned int region_var;

  private:
    void copy(const icancloud_App_MEM_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const icancloud_App_MEM_Message_Base&);
    // make constructors protected to avoid instantiation
    icancloud_App_MEM_Message_Base(const char *name=NULL, int kind=0);
    icancloud_App_MEM_Message_Base(const icancloud_App_MEM_Message_Base& other);
    // make assignment operator protected to force the user override it
    icancloud_App_MEM_Message_Base& operator=(const icancloud_App_MEM_Message_Base& other);

  public:
    virtual ~icancloud_App_MEM_Message_Base();
    virtual icancloud_App_MEM_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class icancloud_App_MEM_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getMemSize() const;
    virtual void setMemSize(unsigned int memSize);
    virtual unsigned int getRegion() const;
    virtual void setRegion(unsigned int region);
};


#endif // ifndef _ICANCLOUD_APP_MEM_MESSAGE_M_H_

