//
// Generated file, do not edit! Created by nedtool 4.6 from src/Base/Messages/icancloud_BlockList_Message.msg.
//

#ifndef _ICANCLOUD_BLOCKLIST_MESSAGE_M_H_
#define _ICANCLOUD_BLOCKLIST_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "icancloud_App_IO_Message.h"
	#include "icancloud_File.h"					
// }}

/**
 * Class generated from <tt>src/Base/Messages/icancloud_BlockList_Message.msg:16</tt> by nedtool.
 * <pre>
 * ///
 * /// icancloud Message for disk requests (branch list)
 * ///
 * message icancloud_BlockList_Message extends icancloud_App_IO_Message
 * {
 *     @customize(true);
 * 
 *     icancloud_File file;		// Branch list
 * }
 * </pre>
 *
 * icancloud_BlockList_Message_Base is only useful if it gets subclassed, and icancloud_BlockList_Message is derived from it.
 * The minimum code to be written for icancloud_BlockList_Message is the following:
 *
 * <pre>
 * class icancloud_BlockList_Message : public icancloud_BlockList_Message_Base
 * {
 *   private:
 *     void copy(const icancloud_BlockList_Message& other) { ... }

 *   public:
 *     icancloud_BlockList_Message(const char *name=NULL, int kind=0) : icancloud_BlockList_Message_Base(name,kind) {}
 *     icancloud_BlockList_Message(const icancloud_BlockList_Message& other) : icancloud_BlockList_Message_Base(other) {copy(other);}
 *     icancloud_BlockList_Message& operator=(const icancloud_BlockList_Message& other) {if (this==&other) return *this; icancloud_BlockList_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual icancloud_BlockList_Message *dup() const {return new icancloud_BlockList_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from icancloud_BlockList_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(icancloud_BlockList_Message);
 * </pre>
 */
class icancloud_BlockList_Message_Base : public ::icancloud_App_IO_Message
{
  protected:
    icancloud_File file_var;

  private:
    void copy(const icancloud_BlockList_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const icancloud_BlockList_Message_Base&);
    // make constructors protected to avoid instantiation
    icancloud_BlockList_Message_Base(const char *name=NULL, int kind=0);
    icancloud_BlockList_Message_Base(const icancloud_BlockList_Message_Base& other);
    // make assignment operator protected to force the user override it
    icancloud_BlockList_Message_Base& operator=(const icancloud_BlockList_Message_Base& other);

  public:
    virtual ~icancloud_BlockList_Message_Base();
    virtual icancloud_BlockList_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class icancloud_BlockList_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual icancloud_File& getFile();
    virtual const icancloud_File& getFile() const {return const_cast<icancloud_BlockList_Message_Base*>(this)->getFile();}
    virtual void setFile(const icancloud_File& file);
};


#endif // ifndef _ICANCLOUD_BLOCKLIST_MESSAGE_M_H_

