//
// Generated file, do not edit! Created by nedtool 4.6 from src/Base/Messages/icancloud_App_NET_Message.msg.
//

#ifndef _ICANCLOUD_APP_NET_MESSAGE_M_H_
#define _ICANCLOUD_APP_NET_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "icancloud_Message.h"
			
// }}

/**
 * Class generated from <tt>src/Base/Messages/icancloud_App_NET_Message.msg:15</tt> by nedtool.
 * <pre>
 * ///
 * /// icancloud Message for NET requests
 * ///
 * message icancloud_App_NET_Message extends icancloud_Message
 * {
 *     @customize(true);
 * 
 *     string destinationIP = "";		// Destination IP
 *     string localIP = "";			// Local IP
 *     int destinationPort = 0;		// Destination port
 *     int localPort = 0;				// Local port
 *     string connectionType = "";		// Connection type
 *     unsigned int size = 0;          // Request size
 *     string data = "";          		// Data sended
 *     string virtual_destinationIP = "";
 *     string virtual_localIP = "";
 *     int virtual_user = -1;
 *     int virtual_destinationPort = 0;		// Virtual Destination port
 *     int virtual_localPort = 0;				// Virtual Local port
 *     string fsType = "";						// Type of remote file system
 *     int targetPosition = 1;					// Target Position of remote file system
 * }
 * </pre>
 *
 * icancloud_App_NET_Message_Base is only useful if it gets subclassed, and icancloud_App_NET_Message is derived from it.
 * The minimum code to be written for icancloud_App_NET_Message is the following:
 *
 * <pre>
 * class icancloud_App_NET_Message : public icancloud_App_NET_Message_Base
 * {
 *   private:
 *     void copy(const icancloud_App_NET_Message& other) { ... }

 *   public:
 *     icancloud_App_NET_Message(const char *name=NULL, int kind=0) : icancloud_App_NET_Message_Base(name,kind) {}
 *     icancloud_App_NET_Message(const icancloud_App_NET_Message& other) : icancloud_App_NET_Message_Base(other) {copy(other);}
 *     icancloud_App_NET_Message& operator=(const icancloud_App_NET_Message& other) {if (this==&other) return *this; icancloud_App_NET_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual icancloud_App_NET_Message *dup() const {return new icancloud_App_NET_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from icancloud_App_NET_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(icancloud_App_NET_Message);
 * </pre>
 */
class icancloud_App_NET_Message_Base : public ::icancloud_Message
{
  protected:
    opp_string destinationIP_var;
    opp_string localIP_var;
    int destinationPort_var;
    int localPort_var;
    opp_string connectionType_var;
    unsigned int size_var;
    opp_string data_var;
    opp_string virtual_destinationIP_var;
    opp_string virtual_localIP_var;
    int virtual_user_var;
    int virtual_destinationPort_var;
    int virtual_localPort_var;
    opp_string fsType_var;
    int targetPosition_var;

  private:
    void copy(const icancloud_App_NET_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const icancloud_App_NET_Message_Base&);
    // make constructors protected to avoid instantiation
    icancloud_App_NET_Message_Base(const char *name=NULL, int kind=0);
    icancloud_App_NET_Message_Base(const icancloud_App_NET_Message_Base& other);
    // make assignment operator protected to force the user override it
    icancloud_App_NET_Message_Base& operator=(const icancloud_App_NET_Message_Base& other);

  public:
    virtual ~icancloud_App_NET_Message_Base();
    virtual icancloud_App_NET_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class icancloud_App_NET_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDestinationIP() const;
    virtual void setDestinationIP(const char * destinationIP);
    virtual const char * getLocalIP() const;
    virtual void setLocalIP(const char * localIP);
    virtual int getDestinationPort() const;
    virtual void setDestinationPort(int destinationPort);
    virtual int getLocalPort() const;
    virtual void setLocalPort(int localPort);
    virtual const char * getConnectionType() const;
    virtual void setConnectionType(const char * connectionType);
    virtual unsigned int getSize() const;
    virtual void setSize(unsigned int size);
    virtual const char * getData() const;
    virtual void setData(const char * data);
    virtual const char * getVirtual_destinationIP() const;
    virtual void setVirtual_destinationIP(const char * virtual_destinationIP);
    virtual const char * getVirtual_localIP() const;
    virtual void setVirtual_localIP(const char * virtual_localIP);
    virtual int getVirtual_user() const;
    virtual void setVirtual_user(int virtual_user);
    virtual int getVirtual_destinationPort() const;
    virtual void setVirtual_destinationPort(int virtual_destinationPort);
    virtual int getVirtual_localPort() const;
    virtual void setVirtual_localPort(int virtual_localPort);
    virtual const char * getFsType() const;
    virtual void setFsType(const char * fsType);
    virtual int getTargetPosition() const;
    virtual void setTargetPosition(int targetPosition);
};


#endif // ifndef _ICANCLOUD_APP_NET_MESSAGE_M_H_

