//
// Generated file, do not edit! Created by nedtool 4.6 from src/Base/Messages/icancloud_App_IO_Message.msg.
//

#ifndef _ICANCLOUD_APP_IO_MESSAGE_M_H_
#define _ICANCLOUD_APP_IO_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "icancloud_Message.h"
			
// }}

/**
 * Class generated from <tt>src/Base/Messages/icancloud_App_IO_Message.msg:15</tt> by nedtool.
 * <pre>
 * ///
 * /// icancloud Message for IO requests
 * ///
 * message icancloud_App_IO_Message extends icancloud_Message
 * {
 *     @customize(true);
 * 
 *     string fileName = "";		// File name
 *     unsigned int offset = 0;	// Offset		
 *     unsigned int size = 0;		// Request size
 *     bool isPending = false;		// Is current request pending?			
 *     string nfs_destAddress = "";
 *     int nfs_destPort = - 1;
 *     int nfs_id = - 1;
 *     string nfs_type = "";
 *     int nfs_requestSize_KB = -1;
 *     int nfs_connectionID = -1;
 * }
 * </pre>
 *
 * icancloud_App_IO_Message_Base is only useful if it gets subclassed, and icancloud_App_IO_Message is derived from it.
 * The minimum code to be written for icancloud_App_IO_Message is the following:
 *
 * <pre>
 * class icancloud_App_IO_Message : public icancloud_App_IO_Message_Base
 * {
 *   private:
 *     void copy(const icancloud_App_IO_Message& other) { ... }

 *   public:
 *     icancloud_App_IO_Message(const char *name=NULL, int kind=0) : icancloud_App_IO_Message_Base(name,kind) {}
 *     icancloud_App_IO_Message(const icancloud_App_IO_Message& other) : icancloud_App_IO_Message_Base(other) {copy(other);}
 *     icancloud_App_IO_Message& operator=(const icancloud_App_IO_Message& other) {if (this==&other) return *this; icancloud_App_IO_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual icancloud_App_IO_Message *dup() const {return new icancloud_App_IO_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from icancloud_App_IO_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(icancloud_App_IO_Message);
 * </pre>
 */
class icancloud_App_IO_Message_Base : public ::icancloud_Message
{
  protected:
    opp_string fileName_var;
    unsigned int offset_var;
    unsigned int size_var;
    bool isPending_var;
    opp_string nfs_destAddress_var;
    int nfs_destPort_var;
    int nfs_id_var;
    opp_string nfs_type_var;
    int nfs_requestSize_KB_var;
    int nfs_connectionID_var;

  private:
    void copy(const icancloud_App_IO_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const icancloud_App_IO_Message_Base&);
    // make constructors protected to avoid instantiation
    icancloud_App_IO_Message_Base(const char *name=NULL, int kind=0);
    icancloud_App_IO_Message_Base(const icancloud_App_IO_Message_Base& other);
    // make assignment operator protected to force the user override it
    icancloud_App_IO_Message_Base& operator=(const icancloud_App_IO_Message_Base& other);

  public:
    virtual ~icancloud_App_IO_Message_Base();
    virtual icancloud_App_IO_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class icancloud_App_IO_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFileName() const;
    virtual void setFileName(const char * fileName);
    virtual unsigned int getOffset() const;
    virtual void setOffset(unsigned int offset);
    virtual unsigned int getSize() const;
    virtual void setSize(unsigned int size);
    virtual bool getIsPending() const;
    virtual void setIsPending(bool isPending);
    virtual const char * getNfs_destAddress() const;
    virtual void setNfs_destAddress(const char * nfs_destAddress);
    virtual int getNfs_destPort() const;
    virtual void setNfs_destPort(int nfs_destPort);
    virtual int getNfs_id() const;
    virtual void setNfs_id(int nfs_id);
    virtual const char * getNfs_type() const;
    virtual void setNfs_type(const char * nfs_type);
    virtual int getNfs_requestSize_KB() const;
    virtual void setNfs_requestSize_KB(int nfs_requestSize_KB);
    virtual int getNfs_connectionID() const;
    virtual void setNfs_connectionID(int nfs_connectionID);
};


#endif // ifndef _ICANCLOUD_APP_IO_MESSAGE_M_H_

